[config]
model="gpt-4-0613"
git_provider="github"
publish_review=true
verbosity_level=0  # 0,1,2

[pr_reviewer]
require_minimal_and_focused_review=true
require_tests_review=true
require_security_review=true
extended_code_suggestions=false
num_code_suggestions=4


[pr_questions]

[gitlab]
# URL to the gitlab service
gitlab_url = "https://gitlab.com"

# Polling (either proheheject id or namespace/project_name) syntax can be used
projects_to_monitor = [47494341, 'my_user/my_project', 'my_group/my_project']

# Polling trigger
magic_word = "AutoReview"

# Polling interval
polling_interval_seconds = 60